[package]
name = "smtp_client"
version = "0.1.0"
description = "A Tauri App"
authors = ["Sebastian Kaźmierczak <moques93@gmail.com>"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.66.0"

[build-dependencies]
tauri-build = { version = "^2.0.0-alpha.2", features = [] }

[dependencies]
serde_json = "^1.0.94"
serde = { version = "^1.0.152", features = ["derive"] }
tauri = { version = "^2.0.0-alpha.4", features = ["devtools", "shell-open"] }
tokio = { version = "^1.26.0", features = ["macros", "rt-multi-thread"] }
anyhow = "^1.0.69"
async-trait = "^0.1.66"
thiserror = "^1.0.39"
tauri-runtime = "^0.13.0-alpha.2"
orion = { version = "^0.17.4", features = ["safe_api", "serde", "alloc"] }
lettre = "^0.10.3"
typeshare = "^1.0.1"
darkbird = { git = "https://github.com/Rustixir/darkbird", rev = "9b62318" }

rust_utils = { git = "https://github.com/MoQuEs/rust_utils" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
