name: 'Release test'

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: Parse changelog
        id: parse-changelog
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            const current_version = "${{ github.ref_name }}";
            const changelogFile = fs.readFileSync('CHANGELOG.md', { encoding: 'utf8', flag: 'r' });
            
            let start = false;
            let currentChangelog = '';
            let currentChangelogLink = '';
            for (let line of changelogFile.split('\n')) {
              line = line.trim();
            
              if (line.startsWith(`[${current_version}]`)) {
                const match = line.match(/\[.*]: (.*\/(v\d+\.\d+\.\d+)\.\.\.(v\d+\.\d+\.\d+))/);
                currentChangelogLink = `**Full changelog between ${match[2]} and ${match[3]}**: ${match[1]}`;
                continue;
              }
            
              if (line.startsWith(`## [${current_version}]`)) {
                start = true;
                continue;
              }
            
              if (start) {
                if (line.startsWith('## [')) {
                  start = false;
                  continue;
                }
            
                currentChangelog += line + '\n';
              }
            }
            
            return `${currentChangelog.trim()}\n\n${currentChangelogLink}`;

      - name: echo
        run: |
          echo "${{ steps.parse-changelog.outputs.result }}"
