name: 'Release test'

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: get-latest-tag
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - name: fix-get-latest-tag
        id: fix-get-latest-tag
        run: |
          echo "current_version=`cut -c2- <<< "${{ steps.get-latest-tag.outputs.tag }}"`" >> $GITHUB_OUTPUT

      - name: read-the-changelog
        id: read-the-changelog
        uses: 3liz/changelog-release@0.2.0
        with:
          tag_name: ${{ steps.fix-get-latest-tag.outputs.current_version }}

      - name: echo-changelog-entry
        run: |
          echo "${{ steps.read-the-changelog.outputs.markdown }}"