name: 'Release v2'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'

          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'

          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''

          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf build-essential curl wget libssl-dev gobject-2.0 libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libglib2.0-dev libgtk-3-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install frontend dependencies
        run: npm install

      - name: Parse changelog
        id: parse-changelog
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            const current_version = "${{ github.ref_name }}";
            const changelogFile = fs.readFileSync('CHANGELOG.md', { encoding: 'utf8', flag: 'r' });
            
            let start = false;
            let currentChangelog = '';
            let currentChangelogLink = '';
            for (let line of changelogFile.split('\n')) {
              line = line.trim();
            
              if (line.startsWith(`[${current_version}]`)) {
                const match = line.match(/\[.*]: (.*\/(v\d+\.\d+\.\d+)\.\.\.(v\d+\.\d+\.\d+))/);
                currentChangelogLink = `**Full changelog between ${match[2]} and ${match[3]}**: ${match[1]}`;
                continue;
              }
            
              if (line.startsWith(`## [${current_version}]`)) {
                start = true;
                continue;
              }
            
              if (start) {
                if (line.startsWith('## [')) {
                  start = false;
                  continue;
                }
            
                currentChangelog += line + '\n';
              }
            }
            
            return `${currentChangelog.trim()}\n\n${currentChangelogLink}`;

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'SMTP Client v__VERSION__'
          releaseBody: ${{ steps.parse-changelog.outputs.result }}
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
